### PR TITLE
Bug on isValid: false when it should be true

### PR DESCRIPTION
**Pull request by ZijneDwaasheid**

### CODE REVIEW

**Comment by JonasVanHoof** [comment]
@Windvis  
When bumping the ember-submission-form-fields package to latest v2.17.1 in the form-builder application Arne found that the conceptscheme dropdown is not working correctly (displayType selection). Than he found this in the code. At first this does not look right. "isValid when having errors"?  Is this correct or should it be changed? :)

**Review by Windvis — APPROVED** [review]
And not letting my PRs get reviewed bites me again 😄 Sorry about that!

Thanks.

**Comment by Windvis** [comment]
Released as v2.17.2 👍

**Comment by JonasVanHoof** [comment]
> Released as v2.17.2 👍

Thanks!

**Pull request merged**
